name: getx_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  package_info_plus: ^8.3.0
  persistent_bottom_nav_bar: ^6.2.1
  syncfusion_flutter_datagrid: ^29.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
